# Generated by Django 5.0.3 on 2024-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text='gramla')),
                ('ingredients', models.TextField(blank=True, max_length=3000, null=True)),
                ('baked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
